name: GitHub Actions Demo
run-name: "${{ github.actor }} is testing out GitHub Actions ðŸš€"

on:
  push:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger
        run: |
          echo 'Trigger: ${{ github.event_name }}'

      - name: Show runner
        run: |
          echo 'Runner: ${{ runner.os }}'

      - name: Show branch & repo
        run: |
          echo 'Branch: ${{ github.ref }} | Repo: ${{ github.repository }}'

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        id: list_files
        run: |
          ls "${{ github.workspace }}"

      - name: Print step outcome
        run: |
          echo "Outcome of 'list_files' is: ${{ steps.list_files.outcome }}"
