name: GitHub Actions Demo
run-name: "${{ github.actor }} is testing out GitHub Actions"

on:
  push:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger
        shell: bash
        run: echo "Trigger: ${{ github.event_name }}"

      - name: Show runner
        shell: bash
        run: echo "Runner: ${{ runner.os }}"

      - name: Show branch & repo
        shell: bash
        run: echo "Branch: ${{ github.ref }} | Repo: ${{ github.repository }}"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        id: list_files
        shell: bash
        run: ls "${{ github.workspace }}"

      - name: Print step outcome
        shell: bash
        run: echo "Outcome of 'list_files' is: ${{ steps.list_files.outcome }}"
